#!/bin/bash

# Настроить erswitcher для текущего пользователя

# ################################################ #
# Author: Yaroslav O. Kosmina                      #
# E-mail: darviarush@mail.ru                       #
# GitHUB: https://github.com/darviarush/erswitcher #
# ################################################ #

echo <<E1
Сейчас будет установлен erswitcher для текущего пользователя.
E1



#xbindkeys -k

x=<<END
"(Scheme function)"
    m:0x0 + c:127
    Pause 
END

echo "$x" >> ~/.xbindkeysrc
