#!/bin/bash

# Транслитерировать предыдущее слово и поменять раскладку

# ################################################ #
# Author: Yaroslav O. Kosmina                      #
# E-mail: darviarush@mail.ru                       #
# GitHUB: https://github.com/darviarush/erswitcher #
# ################################################ #


#WINDOWID=$(xdotool selectwindow)

#layout=`xset -q | grep LED | awk '{ print $10 }'`

# текущая раскладка
ru=`xset -q | grep -i "led mask" | grep -o "....1..."`

# определяем параметры клавы
layout=`setxkbmap -query | awk '/layout/ {print $2}'`
option=`setxkbmap -query | awk '/options/ {print $2}'`
variant=`setxkbmap -query | awk '/variant/ {print $2}'`

# меняем раскладку



echo hi! > /home/dart/__/erswitcher/x.log
